 @startuml 经济学虚拟仿真实验系统
左边到方向正确
权限管理 --> 担任政府
长方形担任政府{
    (担任政府) --> (政府生产经理)
    (担任政府) --> (政府总经理)
    (担任政府) --> (政府营销经理)
    (担任政府) --> (政府营销经理)
}
权限管理 --> 非担任政府
长方形非担任政府{
    (非担任政府) --> (非政府生产经理)
    (非担任政府) --> (非政府总经理)
    (非担任政府) --> (非政府营销经理)
    (非担任政府) --> (非政府人力经理)
}
长方形经济政策管理{
    (经济政策管理) --> (颁布经济措施):制订并颁布经济政策
    (经济政策管理) --> (查看政策):查看经济政策
}

长方形经济预测{
    (经济预测) --> (提交经济预测结果)
    (经济预测) --> (经济预测状态):查看经济预测参与状态
    (经济预测) --> (经济预测结果):查看当前经济预测结果
}
长方形非经济预测{
    (非经济预测) --> (经济预测状态):查看经济预测参与状态
    (非经济预测) --> (经济预测结果):查看当前经济预测结果
}
长方形订单竞标{
    (订单竞标) --> (提交订单竞标数据)
    (订单竞标) --> (订单竞标状态):查看订单竞标参与状态
    (订单竞标) --> (订单竞选结果):按年份查看各公司的订单竞标结果
    (订单竞标) --> (订单竞选模拟):模拟订单竞选结果
}
长方形土地竞标{
    (土地竞标) --> (土地竞标状态):操作
    (土地竞标状态) --> (开启/结束土地竞标)
    (土地竞标状态) --> (:操作)
    (土地竞标状态) --> (土地竞标结果):按年份查看
    (土地竞标) --> (土地查看):查看土地使用状态
}
长方形芯片竞标{
    (芯片竞标) --> (芯片竞标模拟):模拟芯片竞标结果
    (芯片竞标) --> (芯片竞标状态):操作
    (芯片竞标状态) --> (芯片竞标结果):按年份查看
    (芯片竞标状态) --> (芯片竞标参与状态)
    (芯片竞标状态) --> (开启/结束芯片竞标)
    (芯片竞标) --> (芯片交易):各公司买卖芯片
    (芯片交易) --> (芯片挂牌交易):查看交易市场
    (芯片交易) --> (我的挂牌交易):提交自己的交易信息
    (芯片交易) --> (芯片成交历史):查看交易市场的成交历史
}
长方形劳动力竞标{
    (劳动力竞标) --> (劳动力竞标模拟):模拟劳动力竞标结果
    (劳动力竞标) --> (劳动力竞标状态):操作
    (劳动力竞标状态) --> (劳动力竞标结果):按年份查看
    (劳动力竞标状态) --> (劳动力竞标参与状态)
    (劳动力竞标状态) --> (开启/结束劳动力竞标)
}
@enduml
