@startuml 经济学虚拟仿真实验系统
从左到右方向
权限管理 --> 担任政府
长方形担任政府{
    (担任政府) --> (政府生产经理)
    (担任政府) --> (政府总经理)
    (担任政府) --> (政府营销经理)
    (担任政府) --> (政府人力经理)
}
权限管理 --> 非担任政府
长方形非担任政府{
    (非担任政府) --> (非政府生产经理)
    (非担任政府) --> (非政府总经理)
    (非担任政府) --> (非政府营销经理)
    (非担任政府) --> (非政府人力经理)
}
长方形经济政策管理{
    (担任政府) --> (政府生产经理)
    (担任政府) --> (政府总经理)
}

长方形经济预测{
    (担任政府) --> (政府营销经理)
    (担任政府) --> (政府人力经理)
    (非担任政府) --> (非政府生产经理)
}
长方形非经济预测{
@startuml经济学虚拟仿真实验系统
长方形担任政府
}
query为空
query为空
query为空
query为空
长方形非担任政府
}
query为空
query为空
query为空
query为空
长方形经济政策管理
query为空
}
query为空
长方形经济预测
query为空
query为空
query为空
长方形非经济预测
query为空
query为空
长方形订单竞标
query为空
}
query为空
query为空
query为空
长方形土地竞标
query为空
query为空
}
@enduml
