@startuml 网站主要内容
left to right direction
用户 --> (面试总结)
用户 --> (deepseek):后续待定
用户 --> 项目演示
rectangle 项目演示{
  (项目演示) --> (3d渲染)
  (项目演示) --> (后台系统类)
} 
用户 --> 技术分享
rectangle 技术分享{
  (技术分享) --> (上传文章)
  (技术分享) --> (后端)
  (技术分享) --> (前端)
}
用户 --> 兴趣拓展
rectangle 兴趣拓展{
  (兴趣拓展) --> (人工智能)
  (兴趣拓展) --> (彩铅绘画)
  (兴趣拓展) --> (阅读分享)
  (兴趣拓展) --> (滑板)
}
用户 --> 个人空间
rectangle 个人空间{
  (个人空间) --> (年度规划):publish
  (个人空间) --> (月度回顾):publish
  (个人空间) --> (每日分享):publish
  (个人空间) --> (待办事项):private
}
@enduml